name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python and Poetry
      uses: ./.github/actions/setup-python-poetry

    - name: Run tests
      run: poetry run pytest -v

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python and Poetry
      uses: ./.github/actions/setup-python-poetry

    - name: Run flake8
      run: poetry run flake8 app/ tests/

    - name: Run mypy
      run: poetry run mypy app/

  format-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python and Poetry
      uses: ./.github/actions/setup-python-poetry

    - name: Check code formatting with Black
      run: poetry run black --check app/ tests/
